# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sketch_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import interfaz_2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 656)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/medicina.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_3.setMaxLength(2)
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 2, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 6, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_2.setMaxLength(10)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1, QtCore.Qt.AlignTop)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_2.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.gridLayout_3.addWidget(self.widget_3, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 5, 1, 1, 3)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/126466-multimedia-collection/png/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon1)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.horizontalLayout.addWidget(self.commandLinkButton_2)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/126466-multimedia-collection/png/next-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon2)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.gridLayout_3.addWidget(self.widget, 7, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 3)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page)
        self.label_23.setScaledContents(False)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(300, 300))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../icons/medicina.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_8 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_8.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_3, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_8)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_8)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_13.addWidget(self.label_17, 4, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_8.setMaxLength(2)
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_13.addWidget(self.lineEdit_8, 2, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_13.addWidget(self.lineEdit_9, 1, 1, 1, 3)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_13.addWidget(self.textEdit_3, 6, 1, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.widget_8)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_13.addWidget(self.label_18, 2, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_10.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_10.setMaxLength(10)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_13.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_8)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_8)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 6, 0, 1, 1, QtCore.Qt.AlignTop)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.widget_8)
        self.dateEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_4.setCalendarPopup(True)
        self.dateEdit_4.setDate(QtCore.QDate(2018, 1, 1))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.gridLayout_13.addWidget(self.dateEdit_4, 4, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 4, 2, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_9)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_9)
        self.radioButton_4.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_3.addWidget(self.radioButton_4)
        self.gridLayout_13.addWidget(self.widget_9, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_13.addWidget(self.lineEdit_11, 5, 1, 1, 3)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.commandLinkButton_7 = QtWidgets.QCommandLinkButton(self.widget_10)
        self.commandLinkButton_7.setIcon(icon1)
        self.commandLinkButton_7.setObjectName("commandLinkButton_7")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_7)
        self.commandLinkButton_8 = QtWidgets.QCommandLinkButton(self.widget_10)
        self.commandLinkButton_8.setIcon(icon2)
        self.commandLinkButton_8.setObjectName("commandLinkButton_8")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_8)
        self.gridLayout_13.addWidget(self.widget_10, 7, 1, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.widget_8)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 0, 1, 1, 3)
        self.gridLayout_12.addWidget(self.widget_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_7 = QtWidgets.QWidget(self.page_5)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.commandLinkButton_9 = QtWidgets.QCommandLinkButton(self.widget_7)
        self.commandLinkButton_9.setObjectName("commandLinkButton_9")
        self.gridLayout_15.addWidget(self.commandLinkButton_9, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.commandLinkButton_10 = QtWidgets.QCommandLinkButton(self.widget_7)
        self.commandLinkButton_10.setObjectName("commandLinkButton_10")
        self.gridLayout_15.addWidget(self.commandLinkButton_10, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_7)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_15.addWidget(self.treeWidget, 0, 0, 1, 2)
        self.gridLayout_16.addWidget(self.widget_7, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widget_4 = QtWidgets.QWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.widget_4)
        self.dateEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_6.addWidget(self.dateEdit_3, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_6.addWidget(self.textEdit_2, 3, 1, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 2, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 2, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.widget_4)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_6.addWidget(self.dateEdit_2, 2, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_5.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_5.setSizePolicy(sizePolicy)
        self.commandLinkButton_5.setIcon(icon2)
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.gridLayout_10.addWidget(self.commandLinkButton_5, 0, 1, 1, 1)
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(self.widget_6)
        self.commandLinkButton_6.setIcon(icon1)
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.gridLayout_10.addWidget(self.commandLinkButton_6, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_6, 4, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 1, 1, 3)
        self.gridLayout_17.addWidget(self.widget_4, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.gridLayout_14.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_11.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 22))
        self.menubar.setObjectName("menubar")
        self.menuRehabilitador = QtWidgets.QMenu(self.menubar)
        self.menuRehabilitador.setObjectName("menuRehabilitador")
        self.menuRegsitro = QtWidgets.QMenu(self.menubar)
        self.menuRegsitro.setObjectName("menuRegsitro")
        self.menuPrograma = QtWidgets.QMenu(self.menubar)
        self.menuPrograma.setObjectName("menuPrograma")
        self.menuTerapias = QtWidgets.QMenu(self.menubar)
        self.menuTerapias.setObjectName("menuTerapias")
        self.menuReportes = QtWidgets.QMenu(self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(150, 107))
        self.dockWidget_3.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 267, 573))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 0, 1, 1)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.commandLinkButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.gridLayout_9.addWidget(self.commandLinkButton_3, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_9.addWidget(self.lineEdit_6, 2, 0, 1, 1)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.gridLayout_9.addWidget(self.commandLinkButton_4, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.actionBuscar_registro = QtWidgets.QAction(MainWindow)
        self.actionBuscar_registro.setObjectName("actionBuscar_registro")
        self.actionBuscar_registro_2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/126466-multimedia-collection/png/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuscar_registro_2.setIcon(icon3)
        self.actionBuscar_registro_2.setObjectName("actionBuscar_registro_2")
        self.actionNuevo_registro = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/112154-web-navigation-line-craft/png/add-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo_registro.setIcon(icon4)
        self.actionNuevo_registro.setObjectName("actionNuevo_registro")
        self.actionNuevo_registro_2 = QtWidgets.QAction(MainWindow)
        self.actionNuevo_registro_2.setObjectName("actionNuevo_registro_2")
        self.actionBuscar_registro_3 = QtWidgets.QAction(MainWindow)
        self.actionBuscar_registro_3.setObjectName("actionBuscar_registro_3")
        self.actionTodos_los_registros = QtWidgets.QAction(MainWindow)
        self.actionTodos_los_registros.setObjectName("actionTodos_los_registros")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionLicencia = QtWidgets.QAction(MainWindow)
        self.actionLicencia.setObjectName("actionLicencia")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/112154-web-navigation-line-craft/png/note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo.setIcon(icon5)
        self.actionNuevo.setObjectName("actionNuevo")
        self.action_Existente = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/126466-multimedia-collection/png/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Existente.setIcon(icon6)
        self.action_Existente.setObjectName("action_Existente")
        self.actionNuevo_2 = QtWidgets.QAction(MainWindow)
        self.actionNuevo_2.setObjectName("actionNuevo_2")
        self.actionExistente = QtWidgets.QAction(MainWindow)
        self.actionExistente.setObjectName("actionExistente")
        self.actionIniciarTerapia = QtWidgets.QAction(MainWindow)
        self.actionIniciarTerapia.setIcon(icon)
        self.actionIniciarTerapia.setObjectName("actionIniciarTerapia")
        self.actionPasiva = QtWidgets.QAction(MainWindow)
        self.actionPasiva.setObjectName("actionPasiva")
        self.actionResistiva = QtWidgets.QAction(MainWindow)
        self.actionResistiva.setObjectName("actionResistiva")
        self.actionInformaci_n = QtWidgets.QAction(MainWindow)
        self.actionInformaci_n.setObjectName("actionInformaci_n")
        self.actionActiva_2 = QtWidgets.QAction(MainWindow)
        self.actionActiva_2.setObjectName("actionActiva_2")
        self.actionPasiva_2 = QtWidgets.QAction(MainWindow)
        self.actionPasiva_2.setObjectName("actionPasiva_2")
        self.actionResistiva_2 = QtWidgets.QAction(MainWindow)
        self.actionResistiva_2.setObjectName("actionResistiva_2")
        self.actionGenerarReporte = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/126466-multimedia-collection/png/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerarReporte.setIcon(icon7)
        self.actionGenerarReporte.setObjectName("actionGenerarReporte")
        self.actionGenerar_reporte_de_programa = QtWidgets.QAction(MainWindow)
        self.actionGenerar_reporte_de_programa.setObjectName("actionGenerar_reporte_de_programa")
        self.actionGenerar_historial_del_paciente = QtWidgets.QAction(MainWindow)
        self.actionGenerar_historial_del_paciente.setObjectName("actionGenerar_historial_del_paciente")
        self.actionGenerar_reporte_de_sesi_n_2 = QtWidgets.QAction(MainWindow)
        self.actionGenerar_reporte_de_sesi_n_2.setObjectName("actionGenerar_reporte_de_sesi_n_2")
        self.actionGenerar_reporte_de_programa_2 = QtWidgets.QAction(MainWindow)
        self.actionGenerar_reporte_de_programa_2.setObjectName("actionGenerar_reporte_de_programa_2")
        self.actionGenerar_historial_de_paciente = QtWidgets.QAction(MainWindow)
        self.actionGenerar_historial_de_paciente.setObjectName("actionGenerar_historial_de_paciente")
        self.menuRehabilitador.addAction(self.actionAcerca_de)
        self.menuRehabilitador.addAction(self.actionLicencia)
        self.menuRehabilitador.addSeparator()
        self.menuRehabilitador.addAction(self.actionSalir)
        self.menuRegsitro.addAction(self.actionNuevo_registro_2)
        self.menuRegsitro.addAction(self.actionBuscar_registro_3)
        self.menuRegsitro.addSeparator()
        self.menuRegsitro.addAction(self.actionTodos_los_registros)
        self.menuPrograma.addAction(self.actionNuevo_2)
        self.menuPrograma.addAction(self.actionExistente)
        self.menuTerapias.addSeparator()
        self.menuTerapias.addAction(self.actionActiva_2)
        self.menuTerapias.addAction(self.actionPasiva_2)
        self.menuTerapias.addAction(self.actionResistiva_2)
        self.menuTerapias.addSeparator()
        self.menuTerapias.addAction(self.actionInformaci_n)
        self.menuReportes.addAction(self.actionGenerar_reporte_de_sesi_n_2)
        self.menuReportes.addAction(self.actionGenerar_reporte_de_programa_2)
        self.menuReportes.addAction(self.actionGenerar_historial_de_paciente)
        self.menubar.addAction(self.menuRehabilitador.menuAction())
        self.menubar.addAction(self.menuRegsitro.menuAction())
        self.menubar.addAction(self.menuPrograma.menuAction())
        self.menubar.addAction(self.menuTerapias.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.commandLinkButton_2)
        MainWindow.setTabOrder(self.commandLinkButton_2, self.commandLinkButton)
        MainWindow.setTabOrder(self.commandLinkButton, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.commandLinkButton_3)
        MainWindow.setTabOrder(self.commandLinkButton_3, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.commandLinkButton_4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rehabilitator"))
        self.comboBox.setItemText(0, _translate("MainWindow", "CC"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TI"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Pasaporte"))
        self.label_3.setText(_translate("MainWindow", "Nombre:"))
        self.label_6.setText(_translate("MainWindow", "Genero:"))
        self.label_5.setText(_translate("MainWindow", "Edad:"))
        self.label.setText(_translate("MainWindow", "Ocupación:"))
        self.label_7.setText(_translate("MainWindow", "Observaciones:"))
        self.label_4.setText(_translate("MainWindow", "Fecha:"))
        self.radioButton.setText(_translate("MainWindow", "Femenino"))
        self.radioButton_2.setText(_translate("MainWindow", "Masculino"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.commandLinkButton.setText(_translate("MainWindow", "Continuar"))
        self.label_2.setText(_translate("MainWindow", "DATOS DEL PACIENTE"))
        self.label_23.setText(_translate("MainWindow", "Software para el control de sistema robotizado para rehabilitación de miembros superiores, se implementan bases de datos para la gestión de la información v1.0"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "CC"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "TI"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Pasaporte"))
        self.label_16.setText(_translate("MainWindow", "Nombre:"))
        self.label_17.setText(_translate("MainWindow", "Genero:"))
        self.label_18.setText(_translate("MainWindow", "Edad:"))
        self.label_19.setText(_translate("MainWindow", "Ocupación:"))
        self.label_20.setText(_translate("MainWindow", "Observaciones:"))
        self.label_21.setText(_translate("MainWindow", "Fecha:"))
        self.radioButton_3.setText(_translate("MainWindow", "Femenino"))
        self.radioButton_4.setText(_translate("MainWindow", "Masculino"))
        self.commandLinkButton_7.setText(_translate("MainWindow", "Guardar"))
        self.commandLinkButton_8.setText(_translate("MainWindow", "Continuar"))
        self.label_22.setText(_translate("MainWindow", "DATOS DEL PACIENTE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Datos"))
        self.commandLinkButton_9.setText(_translate("MainWindow", "Ver información"))
        self.commandLinkButton_10.setText(_translate("MainWindow", "Nuevo Programa"))
        self.label_9.setText(_translate("MainWindow", "Sesiones totales"))
        self.label_15.setText(_translate("MainWindow", "Observaciones:"))
        self.label_13.setText(_translate("MainWindow", "Fecha de inicio"))
        self.label_14.setText(_translate("MainWindow", "Fecha de finalización"))
        self.label_12.setText(_translate("MainWindow", "Sesiones por semana"))
        self.commandLinkButton_5.setText(_translate("MainWindow", "Continuar"))
        self.commandLinkButton_6.setText(_translate("MainWindow", "Atrás"))
        self.label_8.setText(_translate("MainWindow", "NUEVO PROGRAMA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Programas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Test Inicial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Avance"))
        self.menuRehabilitador.setTitle(_translate("MainWindow", "Rehabilitador"))
        self.menuRegsitro.setTitle(_translate("MainWindow", "Registros"))
        self.menuPrograma.setTitle(_translate("MainWindow", "Programa"))
        self.menuTerapias.setTitle(_translate("MainWindow", "Terapias"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.label_11.setText(_translate("MainWindow", "Ingrese el número de identificación:"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "Buscar"))
        self.label_10.setText(_translate("MainWindow", "BUSCAR REGISTROS"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "Seleccionar entrada"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Id"))
        self.actionBuscar_registro.setText(_translate("MainWindow", "Buscar registro"))
        self.actionBuscar_registro_2.setText(_translate("MainWindow", "Buscar"))
        self.actionNuevo_registro.setText(_translate("MainWindow", "Nuevo"))
        self.actionNuevo_registro_2.setText(_translate("MainWindow", "Nuevo registro"))
        self.actionBuscar_registro_3.setText(_translate("MainWindow", "Buscar registro"))
        self.actionTodos_los_registros.setText(_translate("MainWindow", "Todos los registros"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de "))
        self.actionLicencia.setText(_translate("MainWindow", "Licencia"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo programa"))
        self.action_Existente.setText(_translate("MainWindow", "Continuar con un programa existente"))
        self.actionNuevo_2.setText(_translate("MainWindow", "Nuevo"))
        self.actionExistente.setText(_translate("MainWindow", "Existente"))
        self.actionIniciarTerapia.setText(_translate("MainWindow", "Iniciar Terapia"))
        self.actionPasiva.setText(_translate("MainWindow", "Pasiva"))
        self.actionResistiva.setText(_translate("MainWindow", "Resistiva"))
        self.actionInformaci_n.setText(_translate("MainWindow", "Información"))
        self.actionActiva_2.setText(_translate("MainWindow", "Activa"))
        self.actionPasiva_2.setText(_translate("MainWindow", "Pasiva"))
        self.actionResistiva_2.setText(_translate("MainWindow", "Resistiva"))
        self.actionGenerarReporte.setText(_translate("MainWindow", "Generar reporte"))
        self.actionGenerar_reporte_de_programa.setText(_translate("MainWindow", "Generar reporte de programa"))
        self.actionGenerar_historial_del_paciente.setText(_translate("MainWindow", "Generar historial del paciente"))
        self.actionGenerar_reporte_de_sesi_n_2.setText(_translate("MainWindow", "Generar reporte de sesión"))
        self.actionGenerar_reporte_de_programa_2.setText(_translate("MainWindow", "Generar reporte de programa"))
        self.actionGenerar_historial_de_paciente.setText(_translate("MainWindow", "Generar historial de paciente"))

    def function(self, MainWindow):
        interfaz_2.funcionalidades(self, MainWindow)

    def addEntry(self, MainWindow):
        interfaz_2.addEntry(self, MainWindow)

    def search(self, MainWindow):
        interfaz_2.search(self, MainWindow)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.function(MainWindow)
    ui.addEntry(MainWindow)
    ui.search(MainWindow)
    MainWindow.show()
